import type { BadgePosition, Settings } from '@shared/types'

export const OUT_W = 1080
export const OUT_H = 1920

/**
 * Safe zones (px, at 1080x1920) that stay clear of the Shorts / Reels UI:
 * top bar, bottom title/caption area and the right-hand action column.
 */
export const SAFE = { side: 64, top: 190, bottom: 440, rightColumn: 200 }

export interface OverlayFile {
  path: string
  position: BadgePosition
  from?: number
  to?: number
  fadeIn?: number
  offsetY?: number
}

export interface GraphOptions {
  settings: Settings
  /** Display dimensions of the source (after SAR and rotation). */
  srcW: number
  srcH: number
  /** Stored dimensions (before SAR). Used to detect anamorphic sources. */
  storedW: number
  storedH: number
  videoStreamIndex: number
  audioStreamIndex?: number
  /** Output frame rate, or null to keep the source rate. */
  fps: number | null
  partDuration: number
  overlays: OverlayFile[]
  /** When set, build a single-frame preview whose clock reads this many seconds into the part. */
  previewOffset?: number
}

export interface Graph {
  /** Extra `-i` inputs (still images) in order, starting at input index 1. */
  inputArgs: string[]
  filterComplex: string
  videoLabel: string
  audioLabel?: string
}

function even(n: number): number {
  return Math.max(2, Math.round(n / 2) * 2)
}

export function hexToFfmpeg(hex: string, alpha?: number): string {
  const clean = hex.replace('#', '').slice(0, 6).padEnd(6, '0')
  return alpha === undefined ? `0x${clean}` : `0x${clean}@${alpha}`
}

/** overlay x/y expressions for a position inside the safe zones. W/H = main, w/h = overlay. */
export function positionExpr(position: BadgePosition, offsetY = 0): { x: string; y: string } {
  const { side, top, bottom, rightColumn } = SAFE
  const dy = offsetY ? (offsetY > 0 ? `+${offsetY}` : `${offsetY}`) : ''
  switch (position) {
    case 'top-left':
      return { x: `${side}`, y: `${top}${dy}` }
    case 'top-center':
      return { x: '(W-w)/2', y: `${top}${dy}` }
    case 'top-right':
      return { x: `W-w-${side}`, y: `${top}${dy}` }
    case 'bottom-left':
      return { x: `${side}`, y: `H-h-${bottom}${dy}` }
    case 'bottom-center':
      return { x: '(W-w)/2', y: `H-h-${bottom}${dy}` }
    case 'bottom-right':
      return { x: `W-w-${rightColumn}`, y: `H-h-${bottom}${dy}` }
  }
}

/**
 * Build the complete -filter_complex string for one part.
 *
 * Video chain:  source -> (fps) -> layout (blur | fill | solid) -> overlays -> progress bar -> yuv420p
 * Audio chain:  source -> loudness normalisation -> 48 kHz stereo
 */
export function buildGraph(o: GraphOptions): Graph {
  const s = o.settings
  const W = OUT_W
  const H = OUT_H
  const chains: string[] = []
  const inputArgs: string[] = []
  const preview = o.previewOffset !== undefined
  const dur = Math.max(0.1, o.partDuration)

  // --- head: timestamps from zero, optional frame rate, fix anamorphic pixels ---
  const head: string[] = [preview ? `setpts=PTS-STARTPTS+${o.previewOffset}/TB` : 'setpts=PTS-STARTPTS']
  if (o.fps) head.push(`fps=${o.fps}`)
  if (o.storedW !== o.srcW || o.storedH !== o.srcH) head.push(`scale=${even(o.srcW)}:${even(o.srcH)}`, 'setsar=1')
  chains.push(`[0:${o.videoStreamIndex}]${head.join(',')}[src]`)

  // --- layout ---
  const aspect = o.srcW / o.srcH
  if (s.layout === 'fill') {
    const x = s.cropFocus === 'left' ? '0' : s.cropFocus === 'right' ? 'iw-ow' : '(iw-ow)/2'
    chains.push(
      `[src]scale=${W}:${H}:force_original_aspect_ratio=increase:flags=lanczos,crop=${W}:${H}:x=${x}:y=(ih-oh)/2,setsar=1[base]`
    )
  } else {
    const scale = Math.min(1.6, Math.max(1, s.fgScale || 1))
    const fgW = even(W * scale)
    const fgH = even(fgW / aspect)
    const cropW = Math.min(fgW, W)
    const cropH = Math.min(fgH, H)
    const fg = `scale=${fgW}:${fgH}:flags=lanczos,crop=${cropW}:${cropH},setsar=1`
    if (s.layout === 'solid') {
      chains.push(`[src]${fg},pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2:color=${hexToFfmpeg(s.padColor)}[base]`)
    } else {
      // Blur at quarter resolution: 16x cheaper and visually identical once scaled back up.
      const qW = W / 4
      const qH = H / 4
      const sigma = Math.round((Math.max(0, Math.min(100, s.blurStrength)) / 100) * 22 * 10) / 10
      const blur = sigma > 0 ? `,gblur=sigma=${sigma}` : ''
      chains.push('[src]split=2[bg][fg]')
      chains.push(
        `[bg]scale=${qW}:${qH}:force_original_aspect_ratio=increase,crop=${qW}:${qH}${blur},scale=${W}:${H}:flags=bicubic,eq=brightness=-0.08:saturation=1.2,setsar=1[bgo]`
      )
      chains.push(`[fg]${fg}[fgo]`)
      chains.push('[bgo][fgo]overlay=x=(W-w)/2:y=(H-h)/2:format=auto[base]')
    }
  }

  // --- overlays (PNG stills generated by the renderer) ---
  // Every still is looped for slightly longer than the part and each overlay uses shortest=1,
  // so the main video is always the stream that ends the graph. An unbounded `-loop 1` would
  // keep ffmpeg running forever: overlay extends its output until its *longest* input ends.
  const stillDuration = (dur + 1).toFixed(3)
  let cur = '[base]'
  let inputIndex = 1
  for (const ov of o.overlays) {
    inputArgs.push('-loop', '1', '-framerate', '25', '-t', stillDuration, '-i', ov.path)
    let src = `[${inputIndex}:v]`
    const hasWindow = ov.from !== undefined || ov.to !== undefined
    if (!preview && ov.fadeIn && ov.from !== undefined) {
      chains.push(`[${inputIndex}:v]format=rgba,fade=t=in:st=${ov.from}:d=${ov.fadeIn}:alpha=1[ov${inputIndex}]`)
      src = `[ov${inputIndex}]`
    }
    const { x, y } = positionExpr(ov.position, ov.offsetY)
    let f = `${cur}${src}overlay=x=${x}:y=${y}:format=auto:shortest=1`
    if (hasWindow) {
      const from = ov.from ?? 0
      const to = ov.to ?? dur + 1
      f += `:enable='between(t,${from},${to})'`
    }
    chains.push(`${f}[o${inputIndex}]`)
    cur = `[o${inputIndex}]`
    inputIndex++
  }

  // --- progress bar: a full-width strip that slides in from the left as time passes ---
  if (s.progressBarEnabled) {
    const h = 10
    chains.push(`color=c=${hexToFfmpeg(s.progressBarColor)}:s=${W}x${h}:r=25:d=${stillDuration}[bar]`)
    chains.push(`${cur}[bar]overlay=x=-${W}+${W}*t/${dur.toFixed(3)}:y=${H - h}:eval=frame:format=auto:shortest=1[pb]`)
    cur = '[pb]'
  }

  chains.push(`${cur}format=yuv420p[vout]`)

  // --- audio ---
  let audioLabel: string | undefined
  if (o.audioStreamIndex !== undefined && !preview) {
    const a: string[] = ['asetpts=PTS-STARTPTS']
    if (s.normalizeAudio) a.push('loudnorm=I=-14:TP=-1.5:LRA=11')
    a.push('aresample=48000', 'aformat=sample_fmts=fltp:channel_layouts=stereo')
    chains.push(`[0:${o.audioStreamIndex}]${a.join(',')}[aout]`)
    audioLabel = '[aout]'
  }

  return { inputArgs, filterComplex: chains.join(';'), videoLabel: '[vout]', audioLabel }
}
